### ISSUE TITLE
You can add an example project?

### ISSUE THREAD

**Issue by xhzengAIB** [k06a/LaunchScreenViewController#1]
@k06a

**Comment by k06a** [comment]
I'll add it today

**Comment by xhzengAIB** [comment]
@k06a 

would Your demo create finished?

Jack

**Comment by k06a** [comment]
Added example project, but it have strange issue.
Looks like screenshot appears 20px lefter then needed.

**Comment by xhzengAIB** [comment]
@k06a 
yet! i testing the demo

**Comment by k06a** [comment]
20px shift was fixed https://github.com/k06a/LaunchScreenViewController/commit/5f730a4a005a68e92680b66bf615004012e65e72

And I think this issue can be closed :)

**Comment by xhzengAIB** [comment]
thank you!

**Comment by k06a** [comment]
@xhzengAIB you are welcome!

**Comment by xhzengAIB** [comment]
@k06a 
Should be I make friends?

whatApp:+8615915895880
