### ISSUE TITLE
Strange movement on Xcode 6.2

### ISSUE THREAD

**Issue by phemka** [k06a/LaunchScreenViewController#2]
On launch, there is an movement that show the view shifting on the left.
Tested on the simulator for every device with your exemple and in my app.

**Comment by k06a** [comment]
Strange bug, trying to solve it.

**Comment by k06a** [comment]
@phemka please check new 0.0.5 version

**Comment by phemka** [comment]
Yes ! Works perfectly.

**Comment by k06a** [comment]
@phemka thanks for feedback! :+1:
